//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MVC_Crud_Entity_Framework.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class studydbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new studydbEntities object using the connection string found in the 'studydbEntities' section of the application configuration file.
        /// </summary>
        public studydbEntities() : base("name=studydbEntities", "studydbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new studydbEntities object.
        /// </summary>
        public studydbEntities(string connectionString) : base(connectionString, "studydbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new studydbEntities object.
        /// </summary>
        public studydbEntities(EntityConnection connection) : base(connection, "studydbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="studydbModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="rollno">Initial value of the rollno property.</param>
        public static Student CreateStudent(global::System.Decimal rollno)
        {
            Student student = new Student();
            student.rollno = rollno;
            return student;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal rollno
        {
            get
            {
                return _rollno;
            }
            set
            {
                if (_rollno != value)
                {
                    OnrollnoChanging(value);
                    ReportPropertyChanging("rollno");
                    _rollno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rollno");
                    OnrollnoChanged();
                }
            }
        }
        private global::System.Decimal _rollno;
        partial void OnrollnoChanging(global::System.Decimal value);
        partial void OnrollnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sname
        {
            get
            {
                return _sname;
            }
            set
            {
                OnsnameChanging(value);
                ReportPropertyChanging("sname");
                _sname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sname");
                OnsnameChanged();
            }
        }
        private global::System.String _sname;
        partial void OnsnameChanging(global::System.String value);
        partial void OnsnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> sem
        {
            get
            {
                return _sem;
            }
            set
            {
                OnsemChanging(value);
                ReportPropertyChanging("sem");
                _sem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sem");
                OnsemChanged();
            }
        }
        private Nullable<global::System.Decimal> _sem;
        partial void OnsemChanging(Nullable<global::System.Decimal> value);
        partial void OnsemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String course
        {
            get
            {
                return _course;
            }
            set
            {
                OncourseChanging(value);
                ReportPropertyChanging("course");
                _course = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("course");
                OncourseChanged();
            }
        }
        private global::System.String _course;
        partial void OncourseChanging(global::System.String value);
        partial void OncourseChanged();

        #endregion

    
    }

    #endregion

    
}
