//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="exam", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class exam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal examidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> perField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal rnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> semField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal examid {
            get {
                return this.examidField;
            }
            set {
                if ((this.examidField.Equals(value) != true)) {
                    this.examidField = value;
                    this.RaisePropertyChanged("examid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> per {
            get {
                return this.perField;
            }
            set {
                if ((this.perField.Equals(value) != true)) {
                    this.perField = value;
                    this.RaisePropertyChanged("per");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal rno {
            get {
                return this.rnoField;
            }
            set {
                if ((this.rnoField.Equals(value) != true)) {
                    this.rnoField = value;
                    this.RaisePropertyChanged("rno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> sem {
            get {
                return this.semField;
            }
            set {
                if ((this.semField.Equals(value) != true)) {
                    this.semField = value;
                    this.RaisePropertyChanged("sem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stud", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class stud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string courseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal rnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string snameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string course {
            get {
                return this.courseField;
            }
            set {
                if ((object.ReferenceEquals(this.courseField, value) != true)) {
                    this.courseField = value;
                    this.RaisePropertyChanged("course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal rno {
            get {
                return this.rnoField;
            }
            set {
                if ((this.rnoField.Equals(value) != true)) {
                    this.rnoField = value;
                    this.RaisePropertyChanged("rno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sname {
            get {
                return this.snameField;
            }
            set {
                if ((object.ReferenceEquals(this.snameField, value) != true)) {
                    this.snameField = value;
                    this.RaisePropertyChanged("sname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICRUDService")]
    public interface ICRUDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDService/InsertExam", ReplyAction="http://tempuri.org/ICRUDService/InsertExamResponse")]
        string InsertExam(MvcApplication2.ServiceReference1.exam ee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDService/UpdateExam", ReplyAction="http://tempuri.org/ICRUDService/UpdateExamResponse")]
        string UpdateExam(MvcApplication2.ServiceReference1.exam ee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDService/SearchExam", ReplyAction="http://tempuri.org/ICRUDService/SearchExamResponse")]
        MvcApplication2.ServiceReference1.exam SearchExam(int eid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDService/DeleteExam", ReplyAction="http://tempuri.org/ICRUDService/DeleteExamResponse")]
        string DeleteExam(int eid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDService/showallexam", ReplyAction="http://tempuri.org/ICRUDService/showallexamResponse")]
        MvcApplication2.ServiceReference1.exam[] showallexam();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDService/InsertStud", ReplyAction="http://tempuri.org/ICRUDService/InsertStudResponse")]
        string InsertStud(MvcApplication2.ServiceReference1.stud ss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDService/UpdateStud", ReplyAction="http://tempuri.org/ICRUDService/UpdateStudResponse")]
        string UpdateStud(MvcApplication2.ServiceReference1.stud ss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDService/SearchStud", ReplyAction="http://tempuri.org/ICRUDService/SearchStudResponse")]
        MvcApplication2.ServiceReference1.stud SearchStud(int sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDService/DeleteStud", ReplyAction="http://tempuri.org/ICRUDService/DeleteStudResponse")]
        string DeleteStud(int sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDService/showallstud", ReplyAction="http://tempuri.org/ICRUDService/showallstudResponse")]
        MvcApplication2.ServiceReference1.stud[] showallstud();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRUDServiceChannel : MvcApplication2.ServiceReference1.ICRUDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRUDServiceClient : System.ServiceModel.ClientBase<MvcApplication2.ServiceReference1.ICRUDService>, MvcApplication2.ServiceReference1.ICRUDService {
        
        public CRUDServiceClient() {
        }
        
        public CRUDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRUDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertExam(MvcApplication2.ServiceReference1.exam ee) {
            return base.Channel.InsertExam(ee);
        }
        
        public string UpdateExam(MvcApplication2.ServiceReference1.exam ee) {
            return base.Channel.UpdateExam(ee);
        }
        
        public MvcApplication2.ServiceReference1.exam SearchExam(int eid) {
            return base.Channel.SearchExam(eid);
        }
        
        public string DeleteExam(int eid) {
            return base.Channel.DeleteExam(eid);
        }
        
        public MvcApplication2.ServiceReference1.exam[] showallexam() {
            return base.Channel.showallexam();
        }
        
        public string InsertStud(MvcApplication2.ServiceReference1.stud ss) {
            return base.Channel.InsertStud(ss);
        }
        
        public string UpdateStud(MvcApplication2.ServiceReference1.stud ss) {
            return base.Channel.UpdateStud(ss);
        }
        
        public MvcApplication2.ServiceReference1.stud SearchStud(int sid) {
            return base.Channel.SearchStud(sid);
        }
        
        public string DeleteStud(int sid) {
            return base.Channel.DeleteStud(sid);
        }
        
        public MvcApplication2.ServiceReference1.stud[] showallstud() {
            return base.Channel.showallstud();
        }
    }
}
