<?xml version="1.0" encoding="utf-8"?><Database Name="employeesdb" Class="employeesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\employeesdb.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="external2015_employee.Properties.Settings" SettingsPropertyName="employeesdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblemlpoyees" Member="tblemlpoyees">
    <Type Name="tblemlpoyee">
      <Column Name="employeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="employeeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="salary" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="number" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>