<?xml version="1.0" encoding="utf-8"?><Database Name="Products" Class="ProductsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Products.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProductsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CustomerTB" Member="CustomerTBs">
    <Type Name="CustomerTB">
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="CustomerTB_OrderTB" Member="OrderTBs" ThisKey="CustomerId" OtherKey="CustomerId" Type="OrderTB" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetailTB" Member="OrderDetailTBs">
    <Type Name="OrderDetailTB">
      <Column Name="OrderDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OrderTB_OrderDetailTB" Member="OrderTB" ThisKey="OrderId" OtherKey="OrderId" Type="OrderTB" IsForeignKey="true" />
      <Association Name="ProductsTB_OrderDetailTB" Member="ProductsTB" ThisKey="ProductId" OtherKey="ProductId" Type="ProductsTB" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderTB" Member="OrderTBs">
    <Type Name="OrderTB">
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="OrderTB_OrderDetailTB" Member="OrderDetailTBs" ThisKey="OrderId" OtherKey="OrderId" Type="OrderDetailTB" />
      <Association Name="CustomerTB_OrderTB" Member="CustomerTB" ThisKey="CustomerId" OtherKey="CustomerId" Type="CustomerTB" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductsTB" Member="ProductsTBs">
    <Type Name="ProductsTB">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ProductsTB_OrderDetailTB" Member="OrderDetailTBs" ThisKey="ProductId" OtherKey="ProductId" Type="OrderDetailTB" />
    </Type>
  </Table>
</Database>